version: "3.7"
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8010:3000"
    volumes:
      - ./backend:/app    
    # command: npm run dev
    depends_on:
      - mongodb
    networks:
      - notemaker_network

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "8020:27017"
    restart: unless-stopped
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123456
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 1m
      timeout: 20s
      retries: 5
      start_period: 30s
    networks:
      - notemaker_network


  mongo-express:
    image: mongo-express
    container_name: mongodb-interface
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root123456
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_OPTIONS_EDITORTHEME=material-ocean
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb
    ports:
      - 8030:8081
    healthcheck:
      test: wget --quiet --tries=3 --spider http://admin:admin@localhost:8081 || exit 1
      interval: 1m
      timeout: 20s
      retries: 5
      start_period: 30s
    volumes:
      - ./db_interface:/data
    restart: unless-stopped
    networks:
      - notemaker_network

networks:
  notemaker_network:
    driver: bridge